<definitions xmlns:tns="http://webservice.sandbox.ivj.br/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://webservice.sandbox.ivj.br/">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://webservice.sandbox.ivj.br/"
				schemaLocation="../xsd/book.xsd" />
		</xsd:schema>
	</types>
	<message name="createBook">
		<part name="arg0" type="tns:book" />
	</message>
	<message name="createBookResponse">
		<part name="return" type="tns:book" />
	</message>
	<portType name="BookWS">
		<operation name="createBook">
			<input xmlns:ns1="http://www.w3.org/2007/05/addressing/metadata"
				ns1:Action="http://webservice.sandbox.ivj.br/BookWS/createBookRequest"
				message="tns:createBook" />
			<output xmlns:ns2="http://www.w3.org/2007/05/addressing/metadata"
				ns2:Action="http://webservice.sandbox.ivj.br/BookWS/createBookResponse"
				message="tns:createBookResponse" />
		</operation>
	</portType>
</definitions>