INSERT INTO BOOK(BOOK_ID, TITLE, AUTHOR_ID) VALUES (1, 'LEGACY TITLE 1', 1);
INSERT INTO BOOK(BOOK_ID, TITLE, AUTHOR_ID) VALUES (2, 'LEGACY TITLE 2', 2);
INSERT INTO BOOK(BOOK_ID, TITLE, AUTHOR_ID) VALUES (3, 'LEGACY TITLE 3', 1);
INSERT INTO BOOK(BOOK_ID, TITLE, AUTHOR_ID) VALUES (4, 'LEGACY TITLE 4', 2);
INSERT INTO BOOK(BOOK_ID, TITLE, AUTHOR_ID) VALUES (5, 'LEGACY TITLE 5', 1);

INSERT INTO AUTHOR(AUTHOR_ID, NAME) VALUES (1, 'LEGACY AUTHOR 1');
INSERT INTO AUTHOR(AUTHOR_ID, NAME) VALUES (2, 'LEGACY AUTHOR 2');