INSERT INTO BOOK(TITLE, AUTHOR) VALUES ('TITLE 1', 'AUTHOR 1');
INSERT INTO BOOK(TITLE, AUTHOR) VALUES ('TITLE 2', 'AUTHOR 2');
INSERT INTO BOOK(TITLE, AUTHOR) VALUES ('TITLE 3', 'AUTHOR 3');
INSERT INTO BOOK(TITLE, AUTHOR) VALUES ('TITLE 4', 'AUTHOR 4');
INSERT INTO BOOK(TITLE, AUTHOR) VALUES ('TITLE 5', 'AUTHOR 5');